// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tjyedejdpwduiepctufc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRqeWVkZWpkcHdkdWllcGN0dWZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyODAzNTUsImV4cCI6MjA2Mjg1NjM1NX0.WTWWEiA1OYWf0dyS_IzGNxfxCG6xPO7vE383R5nx-1I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);